behaviors:
  Player:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory: null
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 800000
    max_steps: 4000000
    time_horizon: 128
    summary_freq: 1000
    threaded: true
    self_play:
      save_steps: 10000   
      team_change: 80000   
      swap_steps: 1000
      window: 50
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0


